# Generated by Django 2.2 on 2021-07-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pimage',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='images/'),
        ),
    ]
